# Generated by Django 2.2.17 on 2020-12-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('B', 'Básico'), ('P', 'Premium')], max_length=1, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('is_active', models.BooleanField(default=False, verbose_name='Disponible')),
                ('ingredients', models.ManyToManyField(to='pizzas.Ingredient')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
    ]
